name: Packer Validate Check

on:
  pull_request:
    branches:
      - main

jobs:
  packer-validate:
    name: 'Check Packer Validate'
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Packer
      uses: hashicorp/setup-packer@v1

    - name: Run packer Validate
      run: packer validate .