name: Terraform Validation Check

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  terraform-validate:
    name: 'Validate Terraform Configuration'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1

      - name: Terraform Init
        run: terraform init
        
      - name: Run terraform validate
        run: terraform validate
